[package]
name = "interface_crate"
version = "0.1.0"
edition = "2021"

[dependencies]
savefile-abi.path = "../../savefile-abi"
savefile.path = "../../savefile"
savefile-derive.path= "../../savefile-derive"

