[package]
name = "implementation_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
savefile-abi.path = "../../savefile-abi"
savefile.path = "../../savefile"
savefile-derive.path= "../../savefile-derive"
interface_crate = { path = "../interface_crate" }

